install and push using helm

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,7 +54,7 @@ jobs:
            sudo mv s2i /usr/bin
            which s2i
            s2i version
-      - name: install helm
+      - name: install helm and wildfly helm-charts
         run: |
           echo ===== Installing helm from ${{ env.HELM_URI }} =====
           mkdir /tmp/helm/ && cd /tmp/helm/
@@ -66,69 +66,80 @@ jobs:
            sudo mv ./linux-amd64/helm /usr/bin
            which helm
            helm version
-      - name: Build 
-        run: |
-          echo "Docker Images prior to build wildfly-s2i images"
-          docker image ls
-          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
-          make
-          docker image ls
-      - name: Push to quay.io
-        run: |
-            BUILDER_IMAGE_VERSION=$(./tools/release/get-image-version.sh wildfly/wildfly-centos7)
-            if [ -z ${BUILDER_IMAGE_VERSION} ]; then
-               echo "ERROR no builder image version found"
-               exit 1
-            fi
-            RUNTIME_IMAGE_VERSION=$(./tools/release/get-image-version.sh wildfly/wildfly-runtime-centos7)
-            if [ -z ${RUNTIME_IMAGE_VERSION} ]; then
-               echo "ERROR no builder image version found"
-               exit 1
-            fi
-            BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:${BUILDER_IMAGE_VERSION}"
-            RUNTIME_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION}"
-
-            LATEST_BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest"
-            LATEST_RUNTIME_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7:latest"
-
-            echo Pushing to quay.io
-            echo BUILDER_IMAGE: ${BUILDER_IMAGE}
-            echo RUNTIME_IMAGE: ${RUNTIME_IMAGE}
-            docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
-            docker tag wildfly/wildfly-centos7:${BUILDER_IMAGE_VERSION} ${BUILDER_IMAGE}
-            docker tag wildfly/wildfly-centos7:${BUILDER_IMAGE_VERSION} ${LATEST_BUILDER_IMAGE}
-            docker push ${BUILDER_IMAGE}
-            docker push ${LATEST_BUILDER_IMAGE}
-            docker tag wildfly/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION} ${RUNTIME_IMAGE}
-            docker tag wildfly/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION} ${LATEST_RUNTIME_IMAGE}
-            docker push ${RUNTIME_IMAGE}
-            docker push ${LATEST_RUNTIME_IMAGE}
-      - name: Build PostgreSQL example and push to quay.io
-        run: |
-          s2i build https://github.com/wildfly/wildfly-s2i \
-          -e GALLEON_PROVISION_LAYERS=jaxrs-server,postgresql-datasource,observability \
-          -r master \
-          --context-dir test/test-app-postgres \
-          --loglevel=5 \
-          quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest \
-          wildfly-s2i-builder-image
-          docker tag wildfly-s2i-builder-image:latest quay.io/${{ secrets.QUAY_REPO }}/taskrs-app:latest
-          docker push quay.io/${{ secrets.QUAY_REPO }}/taskrs-app:latest
-      - name: Build Cluster Bench example and push to quay.io
-        run: |
-          s2i build https://github.com/clusterbench/clusterbench.git \
-          -e MAVEN_ARGS_APPEND=-Pee8 \
-          -e S2I_SOURCE_DEPLOYMENTS_DIR=clusterbench-ee8-ear/target \
-          -e GALLEON_PROVISION_LAYERS=cloud-server,web-clustering,ejb,-ejb-local-cache,ejb-dist-cache,jsf \
-          quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest \
-          wildfly-s2i-builder-image
-          docker tag wildfly-s2i-builder-image:latest quay.io/${{ secrets.QUAY_REPO }}/clusterbench:latest
-          docker push quay.io/${{ secrets.QUAY_REPO }}/clusterbench:latest
+           helm repo add wildfly https://docs.wildfly.org/wildfly-charts/
+           helm search repo wildfly
+#      - name: Build 
+#        run: |
+#          echo "Docker Images prior to build wildfly-s2i images"
+#          docker image ls
+#          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
+#          make
+#          docker image ls
+#      - name: Push to quay.io
+#        run: |
+#            BUILDER_IMAGE_VERSION=$(./tools/release/get-image-version.sh wildfly/wildfly-centos7)
+#            if [ -z ${BUILDER_IMAGE_VERSION} ]; then
+#               echo "ERROR no builder image version found"
+#               exit 1
+#            fi
+#            RUNTIME_IMAGE_VERSION=$(./tools/release/get-image-version.sh wildfly/wildfly-runtime-centos7)
+#            if [ -z ${RUNTIME_IMAGE_VERSION} ]; then
+#               echo "ERROR no builder image version found"
+#               exit 1
+#            fi
+#            BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:${BUILDER_IMAGE_VERSION}"
+#            RUNTIME_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION}"
+#
+#            LATEST_BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest"
+#            LATEST_RUNTIME_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7:latest"
+#
+#            echo Pushing to quay.io
+#            echo BUILDER_IMAGE: ${BUILDER_IMAGE}
+#            echo RUNTIME_IMAGE: ${RUNTIME_IMAGE}
+#            docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
+#            docker tag wildfly/wildfly-centos7:${BUILDER_IMAGE_VERSION} ${BUILDER_IMAGE}
+#            docker tag wildfly/wildfly-centos7:${BUILDER_IMAGE_VERSION} ${LATEST_BUILDER_IMAGE}
+#            docker push ${BUILDER_IMAGE}
+#            docker push ${LATEST_BUILDER_IMAGE}
+#            docker tag wildfly/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION} ${RUNTIME_IMAGE}
+#            docker tag wildfly/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION} ${LATEST_RUNTIME_IMAGE}
+#            docker push ${RUNTIME_IMAGE}
+#            docker push ${LATEST_RUNTIME_IMAGE}
+#      - name: Build PostgreSQL example and push to quay.io
+#        run: |
+#          s2i build https://github.com/wildfly/wildfly-s2i \
+#          -e GALLEON_PROVISION_LAYERS=jaxrs-server,postgresql-datasource,observability \
+#          -r master \
+#          --context-dir test/test-app-postgres \
+#          --loglevel=5 \
+#          quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest \
+#          wildfly-s2i-builder-image
+#          docker tag wildfly-s2i-builder-image:latest quay.io/${{ secrets.QUAY_REPO }}/taskrs-app:latest
+#          docker push quay.io/${{ secrets.QUAY_REPO }}/taskrs-app:latest
+#      - name: Build Cluster Bench example and push to quay.io
+#        run: |
+#          s2i build https://github.com/clusterbench/clusterbench.git \
+#          -e MAVEN_ARGS_APPEND=-Pee8 \
+#          -e S2I_SOURCE_DEPLOYMENTS_DIR=clusterbench-ee8-ear/target \
+#          -e GALLEON_PROVISION_LAYERS=cloud-server,web-clustering,ejb,-ejb-local-cache,ejb-dist-cache,jsf \
+#          quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest \
+#          wildfly-s2i-builder-image
+#          docker tag wildfly-s2i-builder-image:latest quay.io/${{ secrets.QUAY_REPO }}/clusterbench:latest
+#          docker push quay.io/${{ secrets.QUAY_REPO }}/clusterbench:latest
       - name: Log in to OpenShift
         uses: redhat-actions/oc-login@v1
         with:
           openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
           openshift_token: ${{ env.OPENSHIFT_TOKEN }}
           insecure_skip_tls_verify: true
+      - name: Deploy quickstart
+        run: |
+          helm install microprofile-config-app \
+          wildfly/wildfly \
+          -f https://raw.githubusercontent.com/wildfly/wildfly-charts/main/examples/microprofile-config/microprofile-config-app.yaml \
+          --set build.s2i.builderImage=quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7 \
+          --set build.s2i.runtimeImage=quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7 \
+          --set build.s2i.version=latest
+          
           
           
